### PR TITLE
Added cp interface function

### PR DESCRIPTION
**Pull request by schwiti6190**
Added interface function for cp stonepickers.

### CODE REVIEW

**Comment by Axel32019** [comment]
Hello @schwiti6190 ,
The Event onCpFuelEmpty is not really useful as it is invoked by isFuelEmpty at FillLevel == 0, better to invoke from isFuelLow(0.1)
Event onCpBroken would be good to raise on damage level >60% at vehicle or at least 1 attached implement.

**Comment by schwiti6190** [comment]
Hi @Axel32019 
If you implement these events, than I would add two setting for the user to configure the threshold for releasing of the driver.

**Comment by Axel32019** [comment]
@schwiti6190 The events are added with above commit, "fake" tests where OK so far.

**Comment by schwiti6190** [comment]
@Axel32019 perfect will implement this in cp then.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip

**Pull request closed without merging**
