### PR TITLE
Fixed Autloader usage with option configurable autloader #437

### PR DESCRIPTION
**Pull request by Achimobil**
I fixed the error in checking if the autoloader spec is active or not

### CODE REVIEW

**Comment by Dzi4d3k** [comment]
@Achimobil not sure if you know but I remember that @Axel32019 wrote somewhere, that pull request should be done to [dev ](https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019) not [main](https://github.com/Stephan-S/FS22_AutoDrive) branch.

**Comment by Tensuko** [comment]
It would be so much easier, if they accept PRs to Main and work on Main with PR by themself, like we do.

**Comment by BizzWareX** [comment]
works fine with these changes 👍

**Comment by Axel32019** [comment]
@Achimobil I add an addtional check to prevent issues in the future and commit it in the dev branch - Thanks for your support

**Comment by Iwan1803** [comment]
@Axel32019 kann hier zugemacht werden?

**Comment by Axel32019** [comment]
Ja, ist integriert.

**Pull request closed without merging**
